/* GENERATED by scripts/optimize-images.mjs — do not edit by hand. */

export type PhotoAsset = {
  /** Emitted widths, descending; each maps to /gallery/<name>-<width>.webp */
  widths: number[]
  /** Inlined 24px WebP shown blurred until the full frame decodes. */
  lqip: string
}

export const photos = {
  'bewakoof-home': {
    widths: [1920, 1280, 800],
    lqip: 'data:image/webp;base64,UklGRsAAAABXRUJQVlA4ILQAAADwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JbACdMoRwH0zAWLd62ZmNtP0+CruG31AA/ud4HoD5idNgwEgJ1LfsEfnW+RgtLXvzp47qPvD+mrLi3bMBz2epIb8P8oebudIuYDKbHbygfP/cUDywiViTs43XPaBIV1HLusN5qGsBpm9FiuCc6/wn7nGzjKsOGHfhRdQzjz+PXNYWBFF+GNVdMFRsp0ceqOmAliVE+X6l7tCAAAA=',
  },
  'bike-road': {
    widths: [1920, 1280, 800],
    lqip: 'data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZwAAQVks16Tf8UAA/uv/P86/WLBKzkxujASm8WXqZ+Av1PSmIj6TZ7Lhi+ZDNFAAAA==',
  },
  'debug-help': {
    widths: [1920, 1280, 800],
    lqip: 'data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JQBdgMYOYxv3np7hNfCWAAP7A9gzzePw5ntXTiMCkqHcdRtZuHro+iOzT62iDcx+vH9lJcNdRQXSD/Wx395xj5JI95UTNZA1aqPaHL9aq5SgXGrU35Wf7eSnonA75kwfV7YH40plEXDMiNNpfHoHJQ3rhJ70XdeUZ3JWoeSSBIYrVgmhs2Ggk+AW/a5sfOjHrcW7Smj7CXAAA',
  },
  'gnani-hero': {
    widths: [1920, 1280, 800],
    lqip: 'data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAACQAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZQAAUqFYcn2fOBtgAP7x4MR7dgxgg79x4DblGn4xAqbZgmpRzJZNMDEQIap1md6ZCmGZ6Lm2sv7tBCljQlcXAAA=',
  },
  'mentor-hall': {
    widths: [1920, 1280, 800],
    lqip: 'data:image/webp;base64,UklGRrQAAABXRUJQVlA4IKgAAAAwBACdASoYAA4APu1iqU2ppaOiMAgBMB2JYwC7AdwLhULjIGfJP8O1VAAA+6MUbRD7aTjxFzleZ24CxTtyOORwgs0+JCkvGhx9aaVoyknNa9+1SOgUQ1WQSfX06gBoLPPCu6Mf6pDqvJ6KSwoDXI6/tWfo3jpnpqUZlz9pWUf7PySDAYjjo4PcR0QenI5LVYuf3TFEMiFQRcNbdoF8AI5cZuug9q5AAAA=',
  },
  'stage-panel': {
    widths: [1920, 1280, 800],
    lqip: 'data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOgMY7atlk4u9k28ZZNafaAAP7kWRnz8tSPAnviEzpNh4rGq0m/YAQbZg3ecPRJPv6RGlKfNRQaso1FyLzzeOI4E0w2IX9jv56JFSMCrC7W0UUKtxLpT1uuHSe9bl3D33EKrvydD7WOXOuV+Hm9IC+6VBPgjZflcKSpH/BlCDwAAAA=',
  },
  'surf-dusk': {
    widths: [1920, 1280, 800],
    lqip: 'data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADQAwCdASoYAA4APu1iqk4ppaQiMAgBMB2JZQAAXpqu/lPzawFjzlAA/svX6pnc7PHCIZ0ZKaP9bnfsDK9AlTpqoiM9W6dWOcCb9aLTovu/PPwJ1RBdBJEzCUSWAA==',
  },
  'trail-bloom': {
    widths: [800],
    lqip: 'data:image/webp;base64,UklGRrwAAABXRUJQVlA4ILAAAACQBACdASoYAA4APu1iqU2ppaOiMAgBMB2JQBAADKQFZVAtG2R6a67H5hL2sYAA/qwLlUpV908o6UOtWTZBVcpm0EfEyw5NV3OGbsgG2dNqruACviBdFc1072XKkThLmGI7Gq2AZZzHR9KK4tVJvsL9uFfr2Ic0YDiq8UOMnTpJcQOydr7wHrLJD526Fe/qEmw0XjYX31dOWEdm+ErOcfNVSdiSq/wiqCwtY9b0qRAAAA==',
  },
  'trek-camp': {
    widths: [800],
    lqip: 'data:image/webp;base64,UklGRqoAAABXRUJQVlA4IJ4AAADwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JYwAAXAWCznpa88613coAAP7wbujQCF5GS6ZvbyDCEwFsMOHB3BtQ8YSkodx88KMEi/0p5ntIeiyOeQGlYCEPs8P5vT+2PbtVeF/33vK9irD2MEv5T8PI1+pPIj47Gph4jlXodwxJX/AgWcuCJ5o+xygc7wF6HPfk2lbxPpoIPB8v6NcgAA==',
  },
  'tribunal-home': {
    widths: [1920, 1280, 800],
    lqip: 'data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAACQAwCdASoYAA4APu1iqU2ppaQiMAgBMB2JZwAAW9vfKBLSaDAgAP7vU6MWtFEEcQAXDVF49Is+FOhYUKHwQbtgPhf7foljiavqoAije6kpRW7tejeFABy1VU8QPJsAAAA=',
  },
  'vakiltech-gsc': {
    widths: [1920, 1280, 800],
    lqip: 'data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAACwAwCdASoYAA4APu1iqk2ppaQiMAgBMB2JYwC/OCHf5i3Kp6ESAADLTjkL1RaCPOtc/d4HH4zdEA7kKTEBA1+xAq3yB4sIRi5LAUFQ/PYHBTvYTKKOXzAyyYhEbFsI6Zip3AAA',
  },
  'vakiltech-hero': {
    widths: [1920, 1280, 800],
    lqip: 'data:image/webp;base64,UklGRswAAABXRUJQVlA4WAoAAAAQAAAAFwAADQAAQUxQSBYAAAABD9D/iAiQCVhMA5E19y5CRP9zD6YYVlA4IJAAAADQBACdASoYAA4APu1iqk2ppaQiMAgBMB2JbACdMoRwN6SAX58ZbQDcWdKRlS5gAAD+7p0mOhDZvmD2BTCJ/SQ0iDwhboZf7sZe9IrJuZFPea2lMV/PIOclqFHVYoPbSqTAHqLzCbvH+vpVS7lMOERLzhYAY1u6Fv1kfihdbIB6heXq28D3F8y4U6tRN5+uoAA=',
  },
  'wellness-health-checks': {
    widths: [1920, 1280, 800],
    lqip: 'data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAwCdASoYAA4APu1kq04ppaQiMAgBMB2JZwAAV96ltle+UKXvXFAA/nG/QPya+AjKu985KaJPgwfnmUIt7qPLGbFJAjTWowNV/VxLP+jGKTwNgAA=',
  },
} satisfies Record<string, PhotoAsset>

export type PhotoName = keyof typeof photos

/** Picks the smallest emitted width that still covers `cssWidth` at this DPR. */
export function photoSrc(name: PhotoName, cssWidth: number, dpr = 1): string {
  const target = cssWidth * Math.min(dpr, 2)
  const { widths } = photos[name]
  const best = [...widths].sort((a, b) => a - b).find((w) => w >= target) ?? Math.max(...widths)
  return `/gallery/${name}-${best}.webp`
}
