/**
 * Builds the gallery's delivery images from the archival originals.
 *
 *   assets/photos/*.jpg  ->  public/gallery/<name>-<width>.webp
 *                        ->  src/content/gallery-manifest.ts (dimensions + LQIP)
 *
 * Every output is a 16/9 frame, matching `.gal-stage`, so the strip-flip's
 * background-position maths lines up regardless of the source crop. Landscape
 * sources are centre-cropped; portrait sources are letterboxed onto a darkened,
 * blurred copy of themselves so nothing gets sliced away.
 *
 * Run with `npm run images` after adding or replacing anything in assets/photos.
 */
import sharp from 'sharp'
import { mkdir, readdir, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const SRC_DIR = join(ROOT, 'assets/photos')
const OUT_DIR = join(ROOT, 'public/gallery')
const MANIFEST = join(ROOT, 'src/content/gallery-manifest.ts')

/** Widths emitted per photo; the component picks one from the stage's box. */
const WIDTHS = [1920, 1280, 800]
const QUALITY = 78
/** Below this aspect ratio a source is treated as portrait and letterboxed. */
const PORTRAIT_MAX_ASPECT = 1.2
/**
 * Above this aspect ratio a source is too wide for a 16/9 crop — a cover-crop
 * would slice off the sides — so it is letterboxed too. Catches panoramas and
 * UI screenshots whose edge content (badges, avatars) must stay in frame.
 */
const LANDSCAPE_MAX_ASPECT = 2.1
/** Width of the inlined blur-up placeholder, in pixels. */
const LQIP_WIDTH = 24

const frameHeight = (width) => Math.round((width * 9) / 16)

/** Fits a portrait source onto a 16/9 frame over a blurred, dimmed backdrop. */
async function letterbox(input, width) {
  const height = frameHeight(width)
  const backdrop = await sharp(input)
    .resize(width, height, { fit: 'cover', position: 'centre' })
    .blur(28)
    .modulate({ brightness: 0.42, saturation: 0.7 })
    .toBuffer()
  const subject = await sharp(input)
    .resize(width, height, { fit: 'inside', withoutEnlargement: false })
    .toBuffer()
  return sharp(backdrop).composite([{ input: subject, gravity: 'centre' }])
}

/** Centre-crops a landscape source to a 16/9 frame. */
function crop(input, width) {
  return sharp(input).resize(width, frameHeight(width), { fit: 'cover', position: 'centre' })
}

async function build(file) {
  const name = file.replace(/\.[^.]+$/, '')
  const input = join(SRC_DIR, file)
  const { width: srcWidth, height: srcHeight } = await sharp(input).metadata()
  const aspect = srcWidth / srcHeight
  const tall = aspect < PORTRAIT_MAX_ASPECT
  // Both tall and ultra-wide sources are letterboxed rather than cropped, so
  // nothing at their edges is lost; only mid-range landscapes get cover-cropped.
  const letterboxed = tall || aspect > LANDSCAPE_MAX_ASPECT
  const frame = (input, width) => (letterboxed ? letterbox(input, width) : crop(input, width))

  // Never upscale far past the source — it only spends bytes on invented pixels.
  // A tall source is height-bound in the frame; every other source is width-bound.
  const ceiling = tall ? (srcHeight * 16) / 9 : srcWidth
  let widths = WIDTHS.filter((w) => w <= ceiling * 1.15)
  if (widths.length === 0) widths = [Math.min(...WIDTHS)]

  const variants = []
  for (const width of widths) {
    const pipeline = await frame(input, width)
    const info = await pipeline.webp({ quality: QUALITY, effort: 6 }).toFile(join(OUT_DIR, `${name}-${width}.webp`))
    variants.push({ width, bytes: info.size })
  }

  // Rendered large-ish then shrunk in a *fresh* pipeline: sharp runs resize
  // before composite, so downscaling in place would undercut the letterbox.
  const framed = await frame(input, LQIP_WIDTH * 8)
  const lqip = await sharp(await framed.toBuffer()).resize(LQIP_WIDTH).webp({ quality: 40 }).toBuffer()

  const total = variants.reduce((sum, v) => sum + v.bytes, 0)
  console.log(
    `${name.padEnd(14)} ${letterboxed ? 'letterbox' : 'crop     '} ` +
      `${widths.join('/')}  ${(total / 1024).toFixed(0)}KB total, lqip ${lqip.length}B`,
  )

  return {
    name,
    widths,
    lqip: `data:image/webp;base64,${lqip.toString('base64')}`,
  }
}

await mkdir(OUT_DIR, { recursive: true })
const files = (await readdir(SRC_DIR)).filter((f) => /\.(jpe?g|png)$/i.test(f)).sort()
const built = []
for (const file of files) built.push(await build(file))

const entries = built
  .map((p) => `  '${p.name}': {\n    widths: [${p.widths.join(', ')}],\n    lqip: '${p.lqip}',\n  },`)
  .join('\n')

await writeFile(
  MANIFEST,
  `/* GENERATED by scripts/optimize-images.mjs — do not edit by hand. */

export type PhotoAsset = {
  /** Emitted widths, descending; each maps to /gallery/<name>-<width>.webp */
  widths: number[]
  /** Inlined ${LQIP_WIDTH}px WebP shown blurred until the full frame decodes. */
  lqip: string
}

export const photos = {
${entries}
} satisfies Record<string, PhotoAsset>

export type PhotoName = keyof typeof photos

/** Picks the smallest emitted width that still covers \`cssWidth\` at this DPR. */
export function photoSrc(name: PhotoName, cssWidth: number, dpr = 1): string {
  const target = cssWidth * Math.min(dpr, 2)
  const { widths } = photos[name]
  const best = [...widths].sort((a, b) => a - b).find((w) => w >= target) ?? Math.max(...widths)
  return \`/gallery/\${name}-\${best}.webp\`
}
`,
  'utf8',
)

console.log(`\n${built.length} photos -> ${OUT_DIR}\n manifest -> ${MANIFEST}`)
